SmileMakersApp/Models/Prescription.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileMakersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public Prescription()
        {
            this.ConsultationCharges = new HashSet<ConsultationCharge>();
            this.Consultations = new HashSet<Consultation>();
            this.PrescribedTreatments = new HashSet<PrescribedTreatment>();
        }
    
        public int id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string prescription_date { get; set; }
        public string oral_examination { get; set; }
        public string medical_history { get; set; }
        public string investigation { get; set; }
        public string advice { get; set; }
    
        public virtual ICollection<ConsultationCharge> ConsultationCharges { get; set; }
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PrescribedTreatment> PrescribedTreatments { get; set; }
    }
}

SmileMakersApp/Controllers/PdfController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using iTextSharp.text;
using System.Linq;
using MvcRazorToPdf;
using SmileMakersApp.Models;
using System.IO;

namespace SmileMakersApp.Controllers
{
    public class PdfController : Controller
    {
        private SmileMakersAppDataEntities db = new SmileMakersAppDataEntities();

        public ActionResult ShowPdf(int id)
        {
            var query = from p in db.Prescriptions
                        where p.id == id
                        select p;

            int pid = query.FirstOrDefault().id;
            string date = query.FirstOrDefault().prescription_date;
            string advice = query.FirstOrDefault().advice;
            string exam = query.FirstOrDefault().oral_examination;
            string history = query.FirstOrDefault().medical_history;
            string investigation = query.FirstOrDefault().investigation;
            string name = query.FirstOrDefault().Patient.name;
            string contact = query.FirstOrDefault().Patient.contact;
            ICollection<PrescribedTreatment> treatments = query.FirstOrDefault().PrescribedTreatments;
            var model = new Prescription
            {
                id = id,
                prescription_date = date,
                advice = advice,
                oral_examination = exam,
                medical_history = history,
                investigation = investigation,
                Patient = new Patient
                {
                    name = name,
                    contact = contact
                },
                PrescribedTreatments = treatments
            };
            return new PdfActionResult(model);
        }

        public ActionResult ShowCharges(int id)
        {
            var query = from p in db.Prescriptions
                        where p.id == id
                        select p;

            int pid = query.FirstOrDefault().id;
            string name = query.FirstOrDefault().Patient.name;
            string contact = query.FirstOrDefault().Patient.contact;
            ICollection<ConsultationCharge> charges = query.FirstOrDefault().ConsultationCharges;
            var model = new Prescription
            {
                id = id,
                Patient = new Patient
                {
                    name = name,
                    contact = contact
                },
                ConsultationCharges = charges
            };
            return new PdfActionResult(model);
        }

        public ActionResult SaveToAppData()
        {
            var model = new PdfExample
            {
                Heading = "Heading",
                Items = new List<BasketItem>
                {
                    new BasketItem
                    {
                        Id = 1,
                        Description = "Item 1",
                        Price = 1.99m
                    },
                    new BasketItem
                    {
                        Id = 2,
                        Description = "Item 2",
                        Price = 2.99m
                    }
                }
            };
            byte[] pdfOutput = ControllerContext.GeneratePdf(model, "IndexWithAccessToDocumentAndWriter");
            string fullPath = Server.MapPath("~/App_Data/FreshlyMade.pdf");

            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            System.IO.File.WriteAllBytes(fullPath, pdfOutput);

            return View("SaveToAppData");
        }

        public ActionResult IndexWithAccessToDocumentAndWriter()
        {
            var model = new PdfExample
            {
                Heading = "Heading",
                Items = new List<BasketItem>
                {
                    new BasketItem
                    {
                        Id = 1,
                        Description = "Item 1",
                        Price = 1.99m
                    },
                    new BasketItem
                    {
                        Id = 2,
                        Description = "Item 2",
                        Price = 2.99m
                    }
                }
            };
            return new PdfActionResult(model, (writer, document) =>
            {
                document.SetPageSize(new Rectangle(500f, 500f, 90));
                document.NewPage();
            });
        }

        public ActionResult IndexWithAccessToDocumentAndWriterDownloadFile()
        {
            var model = new PdfExample
            {
                Heading = "Heading",
                Items = new List<BasketItem>
                {
                    new BasketItem
                    {
                        Id = 1,
                        Description = "Item 1",
                        Price = 1.99m
                    },
                    new BasketItem
                    {
                        Id = 2,
                        Description = "Item 2",
                        Price = 2.99m
                    }
                }
            };
            return new PdfActionResult(model, (writer, document) =>
            {
                document.SetPageSize(new Rectangle(500f, 500f, 90));
                document.NewPage();
            })
            {
                FileDownloadName = "ElanWasHere.pdf"
            };
        }
    }
}

SmileMakersApp/Controllers/PrescriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmileMakersApp.Controllers
{
    public class PrescriptionController : Controller
    {
        //
        // GET: /Prescription/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Prescription/Details
        public ActionResult Details()
        {
            return PartialView("Show");
        }

        //
        // GET: /Prescription/Create
        public ActionResult Create()
        {
            return PartialView("Create");
        }

        //
        // POST: /Prescription/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Prescription/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Prescription/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Prescription/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Prescription/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SmileMakersApp/Views/Prescription/Create.cshtml
<script type="text/javascript">
    $('.clockpicker').clockpicker()
        .find('input').change(function () {
            console.log(this.value);
        });


    if (/mobile/i.test(navigator.userAgent)) {
        $('input').prop('readOnly', true);
    }
</script>



<div ng-controller="prescriptionController">
    <div class="row" style="margin: 30px 0px">
        <div class="col-xs-12 text-center">
            <h3 ng-show="!Update" class="buxton-sketch">Write new prescription for</h3>
            <h3 ng-show="Update" class="buxton-sketch">Update prescription for {{Patient}}</h3>
            <div class="row" ng-show="!Update">
                <div class="col-xs-4 center-block">
                    <input type="text" class="form-control" ng-model="PatientID" typeahead="patient as patient.name + ' (' + patient.contact + ')' for patient in patients | filter:{name:$viewValue}" style="margin-top:20px" /> <br />
                    <p class="input-group">
                        <input type="text" class="form-control" datepicker-popup="{{format}}" ng-model="date" is-open="opened" datepicker-options="dateOptions" ng-required="true" close-text="Close" placeholder="Prescription date" readonly />
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-default" ng-click="open($event)"><i class="glyphicon glyphicon-calendar"></i></button>
                        </span>
                    </p>
                </div>
            </div>  
        </div>
    </div>
    <div class="row" style="margin-bottom:100px">
        <div class="col-xs-3"></div>
        <div class="col-xs-6">
            <textarea class="form-control" placeholder="Oral examination" ng-model="OralExam"></textarea><br />
            <textarea class="form-control" placeholder="Medical history" ng-model="MedHistory"></textarea><br />
            <textarea class="form-control" placeholder="Investigation" ng-model="Investigation"></textarea><br />
            <textarea class="form-control" placeholder="Advice" ng-model="Advice"></textarea><br />

            <div class="row">
                <div class="col-xs-12">
                    <input type="button" class="btn btn-success" value="Save prescription and add treatments" ng-click="save()" ng-show="!Update" />
                    <input type="button" class="btn btn-success" value="Update prescription and add treatments" ng-click="update()" ng-show="Update" />
                    <input type="button" class="btn btn-danger" value="Open prescription in PDF" ng-click="pdfView()" />
                </div>
            </div>
            
        </div>
        <div class="col-xs-3"></div>  
        <!--input type='text' class="form-control datepicker" readonly placeholder="Select appointment date" style="cursor:pointer" ng-model="AppointmentDate" /-->
    </div>
</div>

SmileMakersApp/Views/Prescription/Index.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        $("button.menu-buttons").click(function () {
            $(this).parent().toggleClass("open");
        });

        $("body").click(function (e) {
            if (!$('#search-container').is(e.target) && $('#search-container').has(e.target).length === 0 && $('.open').has(e.target).length === 0) {
                $('#search-container').removeClass('open');
            }
        });
    });
</script>

<div id="pdf2html">
    <div class="row" ng-controller="headerController">
        <div class="col-xs-6" style="height:50px; margin: 20px 0">
            <img src="images/icon.png" width="36" height="44" style="float:left" />
            <h1 class="buxton-sketch" style="font-size: 48px; float:left; margin: 0 20px">Smile Makers Dental Clinic</h1>
        </div>
        <div class="col-xs-6">
            <div style="float:right">
                <a href="/" class="btn btn-primary menu-buttons"><span aria-hidden="true" class="glyphicon glyphicon-home" style="top: calc(100% - 40px)"></span></a>
                <a href="patient/add/0" class="btn btn-danger menu-buttons"><span class="glyphicon glyphicon-user" style="top: calc(100% - 40px)"></span></a>
                <a href="appointment/0" class="btn btn-success menu-buttons"><span class="glyphicon glyphicon-th-list" style="top: calc(100% - 40px)"></span></a>
                <a href="prescription/add/0" class="btn btn-warning menu-buttons"><span class="glyphicon glyphicon-pencil" style="top: calc(100% - 40px)"></span></a>
                <div id="search-container" class="btn-group">
                    <button type="button" class="btn btn-info menu-buttons">
                        <span class="glyphicon glyphicon-search"></span>&nbsp;<span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" style="left:auto; right: 0; width: 366px" role="menu">
                        <li>
                            <div class="input-group" style="padding:5px">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                <input type="text" class="form-control" ng-model="PatientContact" placeholder="Search for patient">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" ng-click="showPatient()"><span class="glyphicon glyphicon-search"></span></button>
                                </span>
                            </div>
                        </li>
                        <li>
                            <div class="input-group" style="padding:5px">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-list-alt"></span></span>
                                <input type="text" class="form-control" ng-model="PrescriptionID" placeholder="Search for prescription">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" ng-click="showPrescription()"><span class="glyphicon glyphicon-search"></span></button>
                                </span>
                            </div>
                        </li>
                        <!--li><a href="patient/0"><span class="glyphicon glyphicon-user"></span>  Search Patient</a></!--li>
                        <li><a href="prescription/0"><span class="glyphicon glyphicon-list-alt"></span>  Search Prescription</a></li-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12" ng-view>
        </div>
    </div>
</div>

SmileMakersApp/Views/Prescription/Show.cshtml
<div ng-controller="showPrescriptionController">
    <div class="row" ng-show="prescription != null">
        <div class="col-xs-7">
            <div class="list-group">
                <div class="row">
                    <div class="col-xs-6">
                        <h3 class="buxton-sketch">Patient's Detail</h3>
                    </div>
                    <div class="col-xs-6">
                        <div class="panel-buttons">
                            <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="showPatient(prescription.Patient[0].id)">
                                <span class="glyphicon glyphicon-share" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="updatePatient(prescription.Patient[0].id)">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="list-group-item">
                    <div class="row">
                        <div class="col-xs-6">
                            <span class="glyphicon glyphicon-user"></span> {{prescription.Patient[0].name}}
                        </div>
                        <div class="col-xs-3">
                            <span class="glyphicon glyphicon-calendar"></span> {{prescription.Patient[0].age}}&nbsp;years old
                        </div>
                        <div class="col-xs-3">
                            <span class="glyphicon glyphicon-phone"></span> {{prescription.Patient[0].contact}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <span class="glyphicon glyphicon-map-marker"></span> {{prescription.Patient[0].address}}
                        </div>
                    </div>
                </div>
            </div>

            <div class="list-group">
                <div class="row">
                    <div class="col-xs-6">
                        <h3 class="buxton-sketch">Prescribed Content</h3>
                    </div>
                    <div class="col-xs-6">
                        <div class="panel-buttons">
                            <a class="btn-default btn" data-ng-href="@Url.Action("ShowPdf", "Pdf")/{{prescription.id}}" target="_blank"><span class="glyphicon glyphicon-print"></span></a>
                            <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="updatePrescription(prescription.id)">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="list-group-item">
                    <div class="row">
                        <div class="col-xs-12">
                            <label>Date:</label> {{prescription.prescription_date}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <label>Oral Examination:</label> {{prescription.oral_examination}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <label>Medical History:</label> {{prescription.medical_history}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <label>Investigation:</label> {{prescription.investigation}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <label>Advice:</label> {{prescription.advice}}
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-xs-6">
                    <h3 class="buxton-sketch">Treatments</h3>
                </div>
                <div class="col-xs-6">
                    <div class="panel-buttons">
                        <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="updateTreatment(prescription.id)">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="row list-group">
                <div class="col-xs-6 list-group-item" ng-repeat="treatments in prescription.PrescribedTreatments" style="margin:10px; width:calc(50% - 20px)">
                    <label style="float:left; width:100%">{{treatments.name}}</label>
                    <div style="width:210px; float:right">
                        <span class="treatment-teeth" style="border-bottom:1px solid #333; border-right:1px solid #333; text-align:right">&nbsp;{{treatments.upper_left}}&nbsp;</span>
                        <span class="treatment-teeth" style="border-bottom:1px solid #333">&nbsp;{{treatments.upper_right}}&nbsp;</span>
                        <span class="treatment-teeth" style="border-right:1px solid #333; text-align:right">&nbsp;{{treatments.lower_left }}&nbsp;</span>
                        <span class="treatment-teeth" style="">&nbsp;{{treatments.lower_right}}&nbsp;</span>
                    </div>
                </div>
            </div>

            <div class="list-group">
                <div class="row">
                    <div class="col-xs-6">
                        <h3 class="buxton-sketch">Total Costing</h3>
                    </div>
                    <div class="col-xs-6">
                        <div class="panel-buttons">
                            <a class="btn-default btn" data-ng-href="@Url.Action("ShowCharges", "Pdf")/{{prescription.id}}" target="_blank"><span class="glyphicon glyphicon-print"></span></a>
                            <button type="button" class="btn btn-default" ng-click="addCharges()">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="list-group-item">
                    <div class="row">
                        <div class="col-xs-4">
                            <label>Surgeon Charge:</label> {{prescription.ConsultationCharges[0].surgeon_charge}}
                        </div>
                        <div class="col-xs-4">
                            <label>Assisstant Charge:</label> {{prescription.ConsultationCharges[0].assisstant_charge}}
                        </div>
                        <div class="col-xs-4">
                            <label>OT Charge:</label> {{prescription.ConsultationCharges[0].ot_charge}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <label>Suction Tube:</label> {{prescription.ConsultationCharges[0].suction_tube}}
                        </div>
                        <div class="col-xs-4">
                            <label>Gloves:</label> {{prescription.ConsultationCharges[0].gloves}}
                        </div>
                        <div class="col-xs-4">
                            <label>Strilization Cost:</label> {{prescription.ConsultationCharges[0].sterilization_cost}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <label>Needle:</label> {{prescription.ConsultationCharges[0].needle}}
                        </div>
                        <div class="col-xs-4">
                            <label>Remar File:</label> {{prescription.ConsultationCharges[0].remar_file}}
                        </div>
                        <div class="col-xs-4">
                            <label>Polishing Bar:</label> {{prescription.ConsultationCharges[0].polishing_bar}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <label>Polishing Paste:</label> {{prescription.ConsultationCharges[0].polishing_paste}}
                        </div>
                        <div class="col-xs-4">
                            <label>Bar:</label> {{prescription.ConsultationCharges[0].bar}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-5">
            <div class="row">
                <div class="col-xs-6">
                    <h3 class="buxton-sketch">Consultations</h3>
                </div>
                <div class="col-xs-6">
                    <div style="position:absolute; right:-5px">
                        <button type="button" class="btn btn-default panel-buttons" aria-label="Left Align" ng-click="addConsultation()">
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                        </button>
                    </div>
                </div>
            </div><br />
            <div ng-repeat="consultation in prescription.Consultations">
                <div class="row">
                    <div class="col-xs-6">
                        <label>{{consultation.consultation_date}}</label>
                    </div>
                    <div class="col-xs-6">
                        <div style="position:absolute; right:10px; top:-5px">
                            <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="updateConsultation(consultation.id)">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="row list-group" ng-repeat="treatmentDetail in consultation.ConsultedTreatments">
                    <div class="col-xs-12 list-group-item" style="float:left; margin:10px; width:calc(100% - 20px)">
                        <label style="float:left; width:100%">{{treatmentDetail.name}}</label>
                        <div style="width:210px; float:right">
                            <span class="treatment-teeth" style="border-bottom: 1px solid #333; border-right: 1px solid #333; text-align: right">&nbsp;{{treatmentDetail.upper_left}}&nbsp;</span>
                            <span class="treatment-teeth" style="border-bottom: 1px solid #333">&nbsp;{{treatmentDetail.upper_right}}&nbsp;</span>
                            <span class="treatment-teeth" style="border-right: 1px solid #333; text-align: right">&nbsp;{{treatmentDetail.lower_left }}&nbsp;</span>
                            <span class="treatment-teeth">&nbsp;{{treatmentDetail.lower_right}}&nbsp;</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>